import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: ".5625rem",
        md: ".375rem",
        sm: ".1875rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      colors: {
        duo: {
          green: {
            DEFAULT: '#58CC02',
            dark: '#46A302',
            light: '#89E219',
            50: '#F7FEE7',
            100: '#ECFCCB',
            200: '#BBF7D0',
            300: '#86EFAC',
            400: '#4ADE80',
            500: '#58CC02',
            600: '#3FAE00',
            700: '#2D7A00',
            800: '#1E5100',
            900: '#0F2800',
          },
          blue: {
            DEFAULT: '#1CB0F6',
            light: '#84D8FF',
            50: '#EFF6FF',
            100: '#DBEAFE',
            200: '#BFDBFE',
            300: '#93C5FD',
            400: '#60A5FA',
            500: '#1CB0F6',
            600: '#0099DB',
            700: '#0077B3',
            800: '#005A8A',
            900: '#003D61',
          },
          red: {
            DEFAULT: '#FF4B4B',
            light: '#FFCECE',
          },
          yellow: {
            DEFAULT: '#FFC800',
            light: '#FFF9E6',
          },
          purple: {
            DEFAULT: '#CE82FF',
            light: '#F3E5FF',
          },
          gray: {
            DEFAULT: '#AFAFAF',
            light: '#E5E5E5',
            dark: '#4B4B4B',
          },
          orange: {
            50: '#FFF7ED',
            100: '#FFEDD5',
            200: '#FED7AA',
            300: '#FDBA74',
            400: '#FB923C',
            500: '#FF9600',
            600: '#EA580C',
            700: '#C2410C',
            800: '#9A3412',
            900: '#7C2D12',
          },
        },
        child: {
          coral: "#FF6B6B",
          turquoise: "#4ECDC4",
          yellow: "#FFD93D",
          green: "#6BCF7F",
          blue: "#4D96FF",
          purple: "#B388FF",
        },
        success: {
          DEFAULT: "#58CC02",
          foreground: "hsl(0 0% 100%)",
        },
        warning: {
          DEFAULT: "#FFC800",
          foreground: "hsl(0 0% 100%)",
        },
        error: {
          DEFAULT: "#FF4B4B",
          foreground: "hsl(0 0% 100%)",
        },
        info: {
          DEFAULT: "#1CB0F6",
          foreground: "hsl(0 0% 100%)",
        },
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        card: {
          DEFAULT: "hsl(var(--card) / <alpha-value>)",
          foreground: "hsl(var(--card-foreground) / <alpha-value>)",
          border: "hsl(var(--card-border) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover) / <alpha-value>)",
          foreground: "hsl(var(--popover-foreground) / <alpha-value>)",
          border: "hsl(var(--popover-border) / <alpha-value>)",
        },
        primary: {
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground) / <alpha-value>)",
          border: "var(--primary-border)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground) / <alpha-value>)",
          border: "var(--secondary-border)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted) / <alpha-value>)",
          foreground: "hsl(var(--muted-foreground) / <alpha-value>)",
          border: "var(--muted-border)",
        },
        accent: {
          DEFAULT: "hsl(var(--accent) / <alpha-value>)",
          foreground: "hsl(var(--accent-foreground) / <alpha-value>)",
          border: "var(--accent-border)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
          border: "var(--destructive-border)",
        },
        ring: "hsl(var(--ring) / <alpha-value>)",
        chart: {
          "1": "hsl(var(--chart-1) / <alpha-value>)",
          "2": "hsl(var(--chart-2) / <alpha-value>)",
          "3": "hsl(var(--chart-3) / <alpha-value>)",
          "4": "hsl(var(--chart-4) / <alpha-value>)",
          "5": "hsl(var(--chart-5) / <alpha-value>)",
        },
        sidebar: {
          ring: "hsl(var(--sidebar-ring) / <alpha-value>)",
          DEFAULT: "hsl(var(--sidebar) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-foreground) / <alpha-value>)",
          border: "hsl(var(--sidebar-border) / <alpha-value>)",
        },
        "sidebar-primary": {
          DEFAULT: "hsl(var(--sidebar-primary) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-primary-foreground) / <alpha-value>)",
          border: "var(--sidebar-primary-border)",
        },
        "sidebar-accent": {
          DEFAULT: "hsl(var(--sidebar-accent) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-accent-foreground) / <alpha-value>)",
          border: "var(--sidebar-accent-border)"
        },
        status: {
          online: "rgb(34 197 94)",
          away: "rgb(245 158 11)",
          busy: "rgb(239 68 68)",
          offline: "rgb(156 163 175)",
        },
      },
      fontFamily: {
        sans: ['Nunito', 'sans-serif'],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
        display: ['Nunito', 'sans-serif'],
        body: ['Nunito', 'sans-serif'],
        arabic: ['Nunito', 'sans-serif'],
        child: ['Nunito', 'sans-serif'],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "bounce-gentle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
        },
        "scale-in": {
          from: { transform: "scale(0)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
        "slide-up": {
          from: { transform: "translateY(20px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        "confetti-fall": {
          "0%": { transform: "translateY(-100%) rotate(0deg)", opacity: "1" },
          "100%": { transform: "translateY(100vh) rotate(720deg)", opacity: "0" },
        },
        "star-pop": {
          "0%": { transform: "scale(0) rotate(-180deg)" },
          "50%": { transform: "scale(1.2) rotate(0deg)" },
          "100%": { transform: "scale(1) rotate(0deg)" },
        },
        shake: {
          "0%, 100%": { transform: "translateX(0)" },
          "10%, 30%, 50%, 70%, 90%": { transform: "translateX(-10px)" },
          "20%, 40%, 60%, 80%": { transform: "translateX(10px)" },
        },
        celebrate: {
          "0%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.2) rotate(5deg)" },
          "100%": { transform: "scale(1) rotate(0deg)" },
        },
        wiggle: {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "pulse-ring": {
          "0%": { transform: "scale(0.95)", opacity: "1" },
          "50%": { transform: "scale(1.05)", opacity: "0.7" },
          "100%": { transform: "scale(0.95)", opacity: "1" },
        },
        "correct-bounce": {
          "0%": { transform: "scale(1)" },
          "30%": { transform: "scale(1.15)" },
          "50%": { transform: "scale(0.95)" },
          "70%": { transform: "scale(1.05)" },
          "100%": { transform: "scale(1)" },
        },
        slideIn: {
          "0%": { transform: "translateY(-20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "bounce-gentle": "bounce-gentle 2s ease-in-out infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "scale-in": "scale-in 0.3s ease-out",
        "slide-up": "slide-up 0.4s ease-out",
        "confetti-fall": "confetti-fall 3s linear forwards",
        "star-pop": "star-pop 0.5s cubic-bezier(0.68, -0.55, 0.265, 1.55)",
        "bounce-soft": "bounce 1s ease-in-out 3",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "shake": "shake 0.5s ease-in-out",
        "celebrate": "celebrate 0.5s ease-in-out",
        "slide-in": "slideIn 0.3s ease-out",
        "fade-in": "fadeIn 0.5s ease-out",
        "wiggle": "wiggle 1s ease-in-out infinite",
        "float": "float 3s ease-in-out infinite",
        "pulse-ring": "pulse-ring 2s ease-in-out infinite",
        "correct-bounce": "correct-bounce 0.6s ease-out",
      },
      boxShadow: {
        "glow": "0 0 30px rgba(139, 92, 246, 0.3)",
        "glow-green": "0 0 20px rgba(88, 204, 2, 0.3)",
        "glow-blue": "0 0 20px rgba(28, 176, 246, 0.3)",
        "glow-orange": "0 0 20px rgba(255, 150, 0, 0.3)",
        "glow-red": "0 0 30px rgba(239, 68, 68, 0.3)",
        "elevated": "0 8px 30px rgba(0, 0, 0, 0.12)",
        "card": "0 2px 12px rgba(0, 0, 0, 0.08)",
        "card-hover": "0 8px 24px rgba(0, 0, 0, 0.12)",
        "duo-button": "0 4px 0 0 #3FAE00",
        "duo-button-blue": "0 4px 0 0 #0099DB",
        "duo-button-orange": "0 4px 0 0 #EA580C",
      },
      backgroundImage: {
        "gradient-modern": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        "gradient-playful": "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
        "gradient-success": "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
        "gradient-warm": "linear-gradient(135deg, #fa709a 0%, #fee140 100%)",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
